version: 2
updates:
  # Python dependencies (pip)
  - package-ecosystem: "pip"
    directory: "/" # Assuming the Python dependencies (requirements.txt) are in the root directory
    schedule:
      interval: "weekly" # Check for updates weekly
